In [22]:
import pandas as pd

In [23]:
df_inscricoes = pd.read_csv('arquivos\\encontreiros.csv', sep=';', encoding='latin-1')
df_financeiro = pd.read_csv('arquivos\\conta_financeira.csv', sep=';')

In [24]:
#Filtrando Inscrições - Cancelado = Não
filtro = df_inscricoes['Cancelada?'] == 'Não'
df_filtrado = df_inscricoes[filtro]

#Filtrando Financeiro - Tipo = C
filtro_financeiro = df_financeiro['Tipo'] == 'C'
df_filtrado_financeiro = df_financeiro[filtro_financeiro]

In [45]:
df_filtrado

,Nome,Tipo do documento,Número do documento,Email,Código da inscrição,Status,Cancelada?,Data da inscrição,Valor,Categoria,...,Qual sua habilidade?,Em qual equipe deseja trabalhar :,Quem realizou a inscrição,Email de quem realizou a inscrição,Tipo do documento de quem realizou a inscrição,Número do documento de quem realizou a inscrição,Check-in em,Nome da inscrição líder,Código da inscrição líder,E-mail da inscrição líder
0,Adriano Sabino Da Silva,CPF,477.160.453-34,joycesabino0@gmail.com,M4Z-EFE-GXK,Ok,Não,23-02-2026 10:13:22,160.0,Normal,...,NaN,Livraria,Joyce Sabino facundo,joycesabino0@gmail.com,NaN,60445689382,NaN,NaN,NaN,NaN
1,Amanda Mendes Evangelista Duarte,CPF,618.276.613-13,amandamevangelista2000@gmail.com,99N-FR8-D3N,Ok,Não,30-01-2026 13:41:32,160.0,Normal,...,NaN,Cafezinho,Arisandra Mendes Dias Evangelista,arisandra.dias@gmail.com,CPF,733.338.593-00,NaN,Arisandra Mendes Dias Evangelista,XZ4-LRW-HTQ,arisandra.dias@gmail.com
4,Ana Valéria Silva De Sousa Lopes,CPF,744.352.483-87,annavalery@hotmail.com,RV6-QLK-SIX,Ok,Não,17-02-2026 10:44:54,160.0,Normal,...,NaN,Cerimonial,Ana Valéria Silva de Sousa Lopes,annavalery@hotmail.com,CPF,744.352.483-87,NaN,NaN,NaN,NaN
5,Antonia Diana Marinho Da Silva,CPF,610.994.413-07,dianamarinhot7@gmail.com,XWB-9NK-NJK,Pendente,Não,06-02-2026 12:49:07,160.0,Normal,...,NaN,Boa Vontade,ANTONIA DIANA MARINHO DA SILVA,dianamarinhot7@gmail.com,CPF,610.994.413-07,NaN,NaN,NaN,NaN
6,Antônio Elivelton Nascimento Silva,CPF,053.071.973-81,romariofrancisco2204@gmail.com,HJ4-K1S-XQ5,Pendente,Não,22-02-2026 10:11:31,160.0,Normal,...,Alimentação,Cafezinho,Romário Francisco Chaves,romariofrancisco2204@gmail.com,CPF,062.117.563-30,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Sandra Silva Brito,CPF,975.658.813-68,gabicoelho082007@gmail.com,5T6-T5W-RE8,Pendente,Não,29-01-2026 11:53:38,160.0,Normal,...,NaN,Bandinha,gabrielly,gabicoelho082007@gmail.com,CPF,634.722.893-92,NaN,NaN,NaN,NaN
81,Simone Da Silva Pereira Sales,CPF,014.194.663-64,richarlissonmatheusdasilva@gmail.com,9VG-74U-77K,Pendente,Não,30-01-2026 23:12:27,160.0,Normal,...,NaN,Bandinha,simone,richarlissonmatheusdasilva@gmail.com,CPF,014.194.663-64,NaN,NaN,NaN,NaN
82,Talia Alves De Carvalho,CPF,079.920.293-21,taliaalvespiercer@gmail.com,M5W-WT8-Q2W,Ok,Não,22-02-2026 14:08:19,160.0,Normal,...,Vendas,Boa Vontade,Talia,taliaalvespiercer@gmail.com,CPF,079.920.293-21,NaN,NaN,NaN,NaN
83,Tiago Vieira De Oliveira,CPF,025.514.333-80,tiagolayane16@gmail.com,KE9-43I-1JS,Pendente,Não,21-01-2026 11:08:21,160.0,Normal,...,NaN,Boa Vontade,Tiago Vieira de Oliveira,tiagolayane16@gmail.com,CPF,025.514.333-80,NaN,NaN,NaN,NaN
86,Vanessa Teles Mendes,CPF,004.612.433-00,vanessatelesmen@gmail.com,5UZ-YHC-EWB,Ok,Não,09-02-2026 20:08:15,160.0,Normal,...,NaN,Livraria,Joyce Sabino facundo,joycesabino0@gmail.com,NaN,60445689382,NaN,NaN,NaN,NaN

# Lista de Equipes

In [25]:
#Selecionar colunas
equipes = df_filtrado[['Nome Crachá (Ele):', 'Telefone (Ele)', 'Nome Crachá (Ela):', 'Telefone (Ela)', 'Em qual equipe deseja trabalhar :', 'Data da inscrição']]

#Renomear colunas
equipes.columns = ['ELE', 'CONTATO ELE', 'ELA', 'CONTATO ELA', 'EQUIPE', 'DATA INSCRIÇÃO']
equipes['ELE'] = equipes['ELE'].str.title()
equipes['ELA'] = equipes['ELA'].str.title()
equipes['DATA INSCRIÇÃO'] = pd.to_datetime(equipes['DATA INSCRIÇÃO'], dayfirst=True)

#Ordenar por equipe
lista_equipes = equipes.sort_values(by=['EQUIPE', 'DATA INSCRIÇÃO'])

#Exportar relatório
lista_equipes.to_excel('export\\lista_equipes.xlsx', index=False)

In [26]:
lista_equipes.info()

<class 'pandas.DataFrame'>
Index: 68 entries, 80 to 38
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ELE             68 non-null     str
 1   CONTATO ELE     67 non-null     str
 2   ELA             68 non-null     str
 3   CONTATO ELA     67 non-null     str
 4   EQUIPE          68 non-null     str
 5   DATA INSCRIÇÃO  68 non-null     datetime64[us]
dtypes: datetime64[us](1), str(5)
memory usage: 3.7 KB

In [27]:
lista_equipes

,ELE,CONTATO ELE,ELA,CONTATO ELA,EQUIPE,DATA INSCRIÇÃO
80,Tom,85985626330,Sandra,85987257854,Bandinha,2026-01-29 11:53:38
69,Hamilton,996440825,Dora,999928464,Bandinha,2026-01-29 12:19:57
58,Adailson,85998114552,Larissa,85999128304,Bandinha,2026-01-29 14:08:59
56,Jota,8599838421,Katyuze,997272316,Bandinha,2026-01-29 15:07:03
53,Wagner,85 989109560,Jô,85 989109560,Bandinha,2026-01-29 21:31:48
...,...,...,...,...,...,...
40,Jarlan,85989682029,Vitória,85989055314,Secretaria,2026-02-09 15:07:39
55,Ivanio,85992280992,Karolina,8599114646,Som e Iluminação,2026-01-19 22:59:25
37,Daniel Sousa,8598678263,Ingrid Karolina,8597383881,Som e Iluminação,2026-01-20 15:03:17
63,Victor Gomes,85994098420,Fernanda Gomes,85994192605,Trânsito,2026-02-08 19:08:46
38,Isaias,85986134223,Glau,85992781818,Trânsito,2026-02-20 08:00:27

# Lista Camisas

In [28]:
#Selecionar colunas
camisas = df_filtrado[['Nome Crachá (Ele):', 'Tamanho Camisa (Ele):', 'Nome Crachá (Ela):', 'Tamanho Camisa (Ela):']]

#Renomear colunas
camisas.columns = ['ELE', 'CAMISA ELE', 'ELA', 'CAMISA ELA']
camisas['ELE'] = camisas['ELE'].str.title()
camisas['ELA'] = camisas['ELA'].str.title()
camisas['CAMISA ELE'] = camisas['CAMISA ELE'].str.upper()
camisas['CAMISA ELA'] = camisas['CAMISA ELA'].str.upper()

#Ordenar por Tamanho
lista_camisas_casal = camisas.sort_values(by=['CAMISA ELE', 'CAMISA ELA'], ascending=[True, True])

#Exportar relatório
lista_camisas_casal.to_excel('export\\lista_camisas_casal.xlsx', index=False)

In [29]:
lista_camisas_casal

                ELE CAMISA ELE               ELA CAMISA ELA
37     Daniel Sousa          G   Ingrid Karolina          G
50     Jose Batista          G       Talita Melo          G
82    Kennedy Sousa          G       Talia Alves          G
86            André          G           Vanessa          G
5            Renato          G             Diana          M
..              ...        ...               ...        ...
57  George Carvalho          M  Larissa Carvalho          P
68          Geovane          M          Marduzia          P
83            Tiago          M           Layanne          P
29           Weyder          P           Luciana          P
38           Isaias          P              Glau          P

[68 rows x 4 columns]

In [30]:
#Selecionar colunas
camisas_ele = df_filtrado[['Nome Crachá (Ele):', 'Tamanho Camisa (Ele):']]
camisas_ela = df_filtrado[['Nome Crachá (Ela):', 'Tamanho Camisa (Ela):']]

#Renomear colunas
camisas_ele.columns = ['NOME', 'TAMANHO']
camisas_ela.columns = ['NOME', 'TAMANHO']
camisas_ele['NOME'] = camisas_ele['NOME'].str.title()
camisas_ela['NOME'] = camisas_ela['NOME'].str.title()
camisas_ele['TAMANHO'] = camisas_ele['TAMANHO'].str.upper()
camisas_ela['TAMANHO'] = camisas_ela['TAMANHO'].str.upper()

#Juntar datasets - camisas_ele + camisas_ela
lista_camisas = pd.concat([camisas_ele, camisas_ela], ignore_index=True)

#Ordenar por Tamanho
lista_camisas = lista_camisas.sort_values(by='TAMANHO', ascending=True)

#Resumo Camisas
resumo_camisas = lista_camisas['TAMANHO'].value_counts()

#Exportar relatório
# lista_camisas.to_excel('export\\lista_camisas.xlsx', index=False)

with pd.ExcelWriter('export\\lista_camisas.xlsx') as writer:
    lista_camisas.to_excel(writer, sheet_name='Lista', index=False)
    resumo_camisas.to_excel(writer, sheet_name='Resumo', index=True)

In [31]:
lista_camisas

             NOME TAMANHO
67          André       G
39   Jonatha Lima       G
41   Jose Batista       G
42        Gleyson       G
43           Renê       G
..            ...     ...
88          Jainy       P
134       Layanne       P
100          Glau       P
82         Dayane       P
107    Jani Teles      PP

[136 rows x 2 columns]

In [32]:
resumo_camisas

TAMANHO
M     44
G     40
P     26
GG    23
G3     1
G4     1
PP     1
Name: count, dtype: int64

# Financeiro

In [33]:
#Selecionar colunas
pagamento = df_filtrado_financeiro[['Pagamento', 'Nome do inscrito', 'Descrição', 'Valor']]

#Renomear colunas
pagamento.columns = ['DATA', 'NOME', 'DESCRIÇÃO', 'VALOR']
pagamento['NOME'] = pagamento['NOME'].str.title()
pagamento['DATA'] = pd.to_datetime(pagamento['DATA'], dayfirst=True)

#Ordenar por Data
relacao_pagamento = pagamento.sort_values(by='DATA')

#Exportar relatório
relacao_pagamento.to_excel('export\\relacao_pagamento.xlsx', index=False)

In [34]:
relacao_pagamento

,DATA,NOME,DESCRIÇÃO,VALOR
0,2026-01-19,Julio Cesar De Oliveira Monteiro,pagamento via pix da inscrição BMR-RN9-54T,160.00
2,2026-01-19,Karolina Oliveira Da Costa,pagamento via pix da inscrição 4N9-M59-LGB,160.00
4,2026-01-20,Ingrid Karolina Dos Santos Pereira,pagamento no cartão de crédito mastercard (com...,160.00
6,2026-01-20,Gerson Rômulo Paiva Das Chagas,pagamento no cartão de crédito mastercard (com...,160.00
8,2026-01-21,Joao Rogênio Guimarães Lima,pagamento no boleto parcela 1/3 da inscrição 9...,53.33
...,...,...,...,...
118,2026-02-21,Jonatha Lima De Souza,pagamento no cartão de crédito visa (com acrés...,160.00
120,2026-02-22,Talia Alves De Carvalho,pagamento no cartão de crédito mastercard (com...,160.00
122,2026-02-22,João Wagner Saraiva Nascimento,pagamento no cartão de crédito mastercard (com...,160.00
124,2026-02-23,Hallison Freire,pagamento via pix da inscrição 7XD-DQU-W5Z,160.00
126,2026-02-23,Adriano Sabino Da Silva,pagamento via pix da inscrição M4Z-EFE-GXK,160.00

# Sorteio

In [35]:
#Lista do sorteio
sorteio_array = pagamento['NOME'].unique()

#Lista em dataframe
sorteio = pd.DataFrame(sorteio_array, columns=['NOME'])

#Ordenar pelo Nome
lista_sorteio = sorteio.sort_values(by='NOME')

#Exportar relatório
lista_sorteio.to_excel('export\\sorteio.xlsx', index=False)

In [36]:
lista_sorteio

                                         NOME
59                    Adriano Sabino Da Silva
49          Ana Valéria Silva De Sousa Lopes
30             Antonia Diana Marinho Da Silva
39          Antonio Nazareno Gomes De Almeida
24            Antônio Nataly De Moraes Sousa
14         Arisandra Mendes Dias Evangelista
5                      Beatriz Carvalho Leão
48              Celia Da Silva Oliveira Alves
31                        Charles Lira Soares
52                             Darlon Freitas
40      Delma Janaína Costa Silva De Freitas
32                  Diego Nascimento Marinho
21                 Dierle Vieira De Oliveira
50                Djane Marinho Do Nascimento
42                    Erick De Sarriune Cysne
23  Francisco Cesar Rodrigues De Araujo Costa
27         Francisco Elves Da Silva Oliveira
34        Francisco Hélio Brigido Dos Santos
17               Francisco Igor Lucena Nunes
7                 Francisco Juniel Lins Braga
38             Francisco Junio Monteiro Silva
26          Francisco Weyder Freitas Santana
16     Georgia Kercia Santos Da Costa Ribeiro
22                  Geraldo Duarte Lira Neto
46                    Germano Bezerra De Melo
3              Gerson Rômulo Paiva Das Chagas
58                            Hallison Freire
2         Ingrid Karolina Dos Santos Pereira
53                Isaias Rodrigues De Pontes
35                       Jarlan Silva De Lima
29                  Jessica De Freitas Santos
4                 Joao Rogênio Guimarães Lima
55                     Jonatha Lima De Souza
20             Jose Francisco Batista De Lima
36               José De Freitas Sousa Filho
6              José Gleyson Alencar Oliveira
25                  José Renê De Sousa Silva
13             José Wagner Hipólito Da Silva
54             João Paulo De Almeida Andrade
57            João Wagner Saraiva Nascimento
0            Julio Cesar De Oliveira Monteiro
12            Jéssica Do Livramento De Sousa
1                  Karolina Oliveira Da Costa
11                  Katyuze De Castro Peixoto
47                  Larissa De Souza Carvalho
10                  Larissa Marques Da Silva
33                 Lorena Gadelha De Almeida
45                         Lucivaldo  Almeida
19           Marduzia Eufrasio Da Silva Lima
9           Maria  Auxiliadora  Costa Pereira
43                Márcia Fernanda Lima Gomes
44                 Paulo Cesar Nogueira Sousa
51                   Rivânia Marcos Da Silva
37                   Romario Francisco Chaves
28         Rosenildo Moreira Fernandes Júnior
15                       Sandra Silva Brito
18             Simone Da Silva Pereira Sales
56                    Talia Alves De Carvalho
8                   Tiago Vieira De Oliveira
41                       Vanessa Teles Mendes

In [37]:
lista_sorteio.info()

<class 'pandas.DataFrame'>
Index: 60 entries, 59 to 41
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOME    60 non-null     str
dtypes: str(1)
memory usage: 960.0 bytes

In [38]:
sorteados = pd.read_csv('arquivos\\sorteados.csv', sep=';')

In [39]:
sorteados['Nome Casal'] = sorteados['Nome Casal'].str.title()

In [40]:
sorteados

                           Nome Casal  Num Ficha
0                     Tiago E Layanne          1
1      Diogo Leite E Beatriz Carvalho          2
2                     Dierle E Dayane          3
3                    César E Gracinha          4
4         Hélio Brigido E Jeane Rocha          5
5                        Romário E Ju          6
6    Berlando Silva E Jessica Freitas          7
7     Diego/Fernanda E Fernanda/Diego          8
8                      Jota E Katyuze          9
9      Gerson Rômulo E Márcia Beatriz         10
10  Alberto Ribeiro E Geórgia Ribeiro         11
11                       Dede E Karen         12
12  Rogênio Guimarães E Lia Guimarães         13
13      Igor Nunes E Jéssica Fernanda         14
14                    Gleyson E Leuda         15
15                     Renê E Luciele         16
16     Daniel Sousa E Ingrid Karolina         17
17    Junio Monteiro E Elisa Monteiro         18
18      Juniel Braga E Silvania Braga         19
19                    Nonato E Nataly         20
20                   Jarlan E Vitória         21
21                Alexandre E Jéssica         22
22                       Naza E Sarah         23
23     Abner Almeida E Lorena Gadelha         24
24                 Carlinhos E Amanda         25
25                      Elves E Jainy         26
26                    Hamilton E Dora         27
27                     Renato E Diana         28
28                   David E Patricia         29
29              Alexandre E Arisandra         29
30                 Geovane E Marduzia         30

In [41]:
# 1. Garantir padronização nas chaves de busca para o Merge
df_filtrado['Nome'] = df_filtrado['Nome'].str.strip().str.title()
lista_sorteio['NOME'] = lista_sorteio['NOME'].str.strip().str.title()

# 2. Realizando o 'PROCV' (Merge) incluindo a coluna da Igreja
lista_sorteio_completa = pd.merge(
    lista_sorteio, 
    df_filtrado[['Nome', 'Nome Crachá (Ele):', 'Telefone (Ele)', 'Nome Crachá (Ela):', 'Telefone (Ela)', 'Igreja em que congregam:']],
    left_on='NOME', 
    right_on='Nome', 
    how='left'
)

# 3. Criando a coluna 'Nome Casal'
lista_sorteio_completa['Nome Casal'] = (
    lista_sorteio_completa['Nome Crachá (Ele):'].str.title() + 
    ' e ' + 
    lista_sorteio_completa['Nome Crachá (Ela):'].str.title()
)

# 4. Selecionando colunas e REMOVENDO DUPLICADOS (Unique)
lista_final = lista_sorteio_completa[['Nome Casal', 'Telefone (Ele)', 'Telefone (Ela)', 'Igreja em que congregam:']]
lista_final = lista_final.drop_duplicates(subset=['Nome Casal']) # <--- Adicionado aqui

# 5. Remoção de quem já foi sorteado
lista_final['NOME_COMPARA'] = lista_final['Nome Casal'].str.upper().str.strip()
sorteados['NOME_COMPARA'] = sorteados['Nome Casal'].str.upper().str.strip()

lista_final_disponivel = lista_final[~lista_final['NOME_COMPARA'].isin(sorteados['NOME_COMPARA'])].copy()

# 6. Limpeza e exportação
lista_final_disponivel.drop(columns=['NOME_COMPARA'], inplace=True)
lista_final_disponivel.to_excel('export\\lista_sorteio.xlsx', index=False)

# Resultados
print(f"Total de casais únicos: {len(lista_final)}")
print(f"Restantes para o sorteio (após remover ganhadores): {len(lista_final_disponivel)}")

lista_final_disponivel

Total de casais únicos: 60
Restantes para o sorteio (após remover ganhadores): 31

,Nome Casal,Telefone (Ele),Telefone (Ela),Igreja em que congregam:
0,Adriano e Valdiana,85989313040,85984225163,Paz Church
1,Junior e Valéria,85989193030,85 987229193,Paz church Fortaleza sede
7,Zé Carlos e Celia Oliveira,85984246971,85987358436,Paz sede
8,Charles e Laiza,85997575209,85986566701,paz sede
9,Darlon Freitas e Vanessa Freitas,"Rua Cidade Ecolgica,",85988365279,paz church sede
10,Freitas Júnior e Delma Freitas,85 8959-7282,85 8416-8113,paz sede
13,Davi e Djane,85985250086,85988319592,Paz church Mucunã
15,Erick Cysne e Ciana,999892830,999892830,sede
22,Weyder e Luciana,85667530,85667530,paz Church mucunã
24,Neto e Dany,85988672393,85987081893,paz church sede
25,Germano Melo e Lilia Delany,85999688646,85999688646,Paz Messejana
27,Hallison e Thalyta,85999216929,85987379791,Paz Church Fortaleza
29,Isaias e Glau,85986134223,85992781818,paz church sede
33,Jonatha Lima e Jani Teles,85999859220,85997133746,Paz Church Mucunã
34,Jose Batista e Talita Melo,89999303590,89999733176,PAZ CHURCH VALENÇA DO PIAUI
38,Wagner e Jô,85 989109560,85 989109560,cede
39,João Paulo e Ana Paula,61981724801,61981723554,Paz Church Sede
40,Wagner e Rejane,85989402215,85981783085,Paz Church Messejana
41,Julio e Mary,85988862931,85986077028,Núcleo Aquiraz
43,Ivanio e Karolina,85992280992,8599114646,Paz Horizonte
45,George Carvalho e Larissa Carvalho,8592043449,8591679947,Ad Messejana Min Fortaleza
46,Adailson e Larissa,85998114552,85999128304,Paz Church Messejana
48,Lucivaldo e Patrícia,85982258171,87974777,núcleo de messejana
51,Victor Gomes e Fernanda Gomes,85994098420,85994192605,Paz Church Sede
52,Pc e Dil,85 9 9669-3418,88 9 9729-5317,CBG Av VI
53,Mikael Lucas e Rivânia Marcos,85 991819375,85991113614,Paz Church Pacajus
55,Junior Moreira e Tatiane Karla,(85)99792-2688,(85)99113-9571,PAZ CHURCH MESSEJANA
56,Tom e Sandra,85985626330,85987257854,Paz Mondubim
57,Vagner e Simone,85987501027,85984210660,AD ALIANÇA PROFÉTICA (ADAP)
58,Kennedy Sousa e Talia Alves,85987958652,85997468644,Paz church Aquiraz
60,André e Vanessa,85999607255,85999607255,Paz church

In [42]:
# 1. Padronização dos nomes das Igrejas
# Remove espaços extras, converte para Title Case (Cada Palavra Iniciada em Maiúscula)
lista_final_disponivel['Igreja em que congregam:'] = lista_final_disponivel['Igreja em que congregam:'].str.strip().str.title()

# 2. Criar a análise por Igreja (Contagem)
analise_igreja = lista_final_disponivel['Igreja em que congregam:'].value_counts().reset_index()
analise_igreja.columns = ['IGREJA', 'QUANTIDADE DE CASAIS']

# 3. Ordenar pela quantidade (do maior para o menor)
analise_igreja = analise_igreja.sort_values(by='QUANTIDADE DE CASAIS', ascending=False)

# 4. Exportar a análise
analise_igreja.to_excel('export\\analise_por_igreja.xlsx', index=False)

# Visualizar o resumo
print("Resumo de Casais por Igreja:")
analise_igreja

Resumo de Casais por Igreja:

                         IGREJA  QUANTIDADE DE CASAIS
0               Paz Church Sede                     5
1                      Paz Sede                     3
2             Paz Church Mucunã                     3
3                    Paz Church                     2
4          Paz Church Messejana                     2
5     Paz Church Fortaleza Sede                     1
6                          Sede                     1
7                 Paz Messejana                     1
8          Paz Church Fortaleza                     1
9   Paz Church Valença Do Piaui                     1
10                         Cede                     1
11               Núcleo Aquiraz                     1
12                Paz Horizonte                     1
13   Ad Messejana Min Fortaleza                     1
14        Paz  Church Messejana                     1
15          Núcleo De Messejana                     1
16                    Cbg Av Vi                     1
17           Paz Church Pacajus                     1
18                 Paz Mondubim                     1
19  Ad Aliança Profética (Adap)                     1
20           Paz Church Aquiraz                     1